### ISSUE TITLE
Unable to Generate tests

### ISSUE THREAD

**Issue by smilinrobin** [hanada31/LAND#1]
Following the instructions on the Readme, I am unable to generate the tests. Error log as below:

 ```
C:\Users\robin\Desktop\LAND> java -jar land.jar
pythonScriptName: operate/1_decompile.py
pythonScriptName: operate/2_instrument.py
pythonScriptName: operate/3_install.py
pythonScriptName: operate/3_install.py
pythonScriptName: operate/4_profile.py
true
runShowExploreMessage!!
C:\Users\robin\Desktop\LAND\files\btime\Infos\currentATG.dot
firstPath not exist
files\btime\Infos\getName.txt: 1 file pushed, 0 skipped. 3.1 MB/s (9398 bytes in 0.003s)
files\btime\Infos\manifestStartFlag.txt: 1 file pushed, 0 skipped. 1.4 MB/s (579 bytes in 0.000s)
profile\btime\profile.txt: 1 file pushed, 0 skipped. 0.7 MB/s (269 bytes in 0.000s)
files\btime\Infos\EditText_values.txt: 1 file pushed, 0 skipped.
adb shell am instrument -e class com.dw.btime.test.MyPrepare -w com.dw.btime.test/android.test.InstrumentationTestRunner
android.util.AndroidException: INSTRUMENTATION_FAILED: com.dw.btime.test/android.test.InstrumentationTestRunner
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.dw.btime.test/android.test.InstrumentationTestRunner}
INSTRUMENTATION_STATUS_CODE: -1
        at com.android.commands.am.Am.runInstrument(Am.java:890)
        at com.android.commands.am.Am.onRun(Am.java:400)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
        at com.android.commands.am.Am.main(Am.java:121)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
rm: /mnt/sdcard/currentATG.dot: No such file or directory
adb: error: remote object '/sdcard/currentATG.dot' does not exist
adb shell am instrument -e class com.dw.btime.test.MyTest -w com.dw.btime.test/android.test.InstrumentationTestRunner
adb: error: remote object '/sdcard/GUIinfo.txt' does not exist
adb: error: remote object '/sdcard/Serialize.txt' does not exist
android.util.AndroidException: INSTRUMENTATION_FAILED: com.dw.btime.test/android.test.InstrumentationTestRunner
        at com.android.commands.am.Am.runInstrument(Am.java:890)
        at com.android.commands.am.Am.onRun(Am.java:400)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
        at com.android.commands.am.Am.main(Am.java:121)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.dw.btime.test/android.test.InstrumentationTestRunner}
INSTRUMENTATION_STATUS_CODE: -1
adb: error: remote object '/sdcard/states.txt' does not exist
rm: /sdcard/states.txt: No such file or directory
adb: error: remote object '/mnt/sdcard/Log.txt' does not exist
adb: error: remote object '/mnt/sdcard/recordEvents.txt' does not exist
adb: error: remote object '/mnt/sdcard/IsFinish.txt' does not exist
adb: error: remote object '/mnt/sdcard/Serialize.txt' does not exist
push file to phone
start exploration

adb shell am instrument -e class com.dw.btime.test.MyPrepare -w com.dw.btime.test/android.test.InstrumentationTestRunner >>Infos\re_auto_file.txt
pull atg, GUI info and ser1

LogTest success!

logCrash success!

adb shell am instrument -e class com.dw.btime.test.MyTest -w com.dw.btime.test/android.test.InstrumentationTestRunner >>Infos\re_auto_file.txt
pull files from phone
pull screenshots
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\robin\Desktop\LAND\operate\Utils.py", line 26, in judgeIsOutCurrentApp
    getInfo(apkName)
  File "C:\Users\robin\Desktop\LAND\operate\getInfos.py", line 29, in getInfo
    f = open(atgfile,"r")
IOError: [Errno 2] No such file or directory: 'files\\btime\\Infos\\currentATG.dot'

Traceback (most recent call last):
  File "operate/5_exploration.py", line 171, in <module>
    fr2 = open(finish_file,'r')
IOError: [Errno 2] No such file or directory: 'files\\btime\\Infos\\IsFinish.txt'
runShowExploreMessage!!
C:\Users\robin\Desktop\LAND\files\btime\Infos\currentATG.dot
firstPath not exist
runShowExploreMessage!!
C:\Users\robin\Desktop\LAND\files\btime\Infos\currentATG.dot
firstPath not exist
runShowExploreMessage!!
C:\Users\robin\Desktop\LAND\files\btime\Infos\currentATG.dot
firstPath not exist
runShowExploreMessage!!
C:\Users\robin\Desktop\LAND\files\btime\Infos\currentATG.dot
firstPath not exist
runShowExploreMessage!!
C:\Users\robin\Desktop\LAND\files\btime\Infos\currentATG.dot
firstPath not exist
runShowExploreMessage!!
C:\Users\robin\Desktop\LAND\files\btime\Infos\currentATG.dot
firstPath not exist
runShowExploreMessage!!
C:\Users\robin\Desktop\LAND\files\btime\Infos\currentATG.dot
firstPath not exist
runShowExploreMessage!!
C:\Users\robin\Desktop\LAND\files\btime\Infos\currentATG.dot
firstPath not exist
runShowExploreMessage!!
C:\Users\robin\Desktop\LAND\files\btime\Infos\currentATG.dot
firstPath not exist
runShowExploreMessage!!
C:\Users\robin\Desktop\LAND\files\btime\Infos\currentATG.dot
firstPath not exist
runShowExploreMessage!!
C:\Users\robin\Desktop\LAND\files\btime\Infos\currentATG.dot
firstPath not exist
runShowExploreMessage!!
C:\Users\robin\Desktop\LAND\files\btime\Infos\currentATG.dot
firstPath not exist
```

**Comment by hanada31** [comment]
This error message seems to relate to the instrumentation of the Robotium framework.
Some vendor systems may conflict with the instrumentation, so it is easier to test apps on an emulator than a device.
The app btime needs an emulator with armv7, so I test another app: aGrep. And it works well without such an error.
Have you ever try other apps, e.g., the app Grep?
![捕获](https://user-images.githubusercontent.com/13084407/89151482-a8f8ae00-d593-11ea-804c-f03571bdca9b.PNG)

**Comment by hanada31** [comment]
This error message seems to relate to the instrumentation of the Robotium framework.
Some vendor systems may conflict with the instrumentation, so it is easier to test apps on an emulator than a device.
The app btime needs an emulator with armv7, so I test another app: aGrep. And it works well without such an error.
Have you ever try other apps, e.g., the app Grep?
![捕获](https://user-images.githubusercontent.com/13084407/89151550-d2b1d500-d593-11ea-839e-5f27d3f49f6b.PNG)

**Comment by hanada31** [comment]
This error message seems to relate to the instrumentation of the Robotium framework.
Some vendor systems may conflict with the instrumentation, so it is easier to test apps on an emulator than a device.
The app btime needs an emulator with armv7, so I test another app: aGrep. And it works well without such an error.
Have you ever try other apps, e.g., the app Grep?
![screenshot](https://user-images.githubusercontent.com/13084407/89151608-f543ee00-d593-11ea-8eed-ea0f61ed7856.PNG)

**Comment by smilinrobin** [comment]
Yes , Ive tried with aGrep APK on an Android emulator, with the same failure results. 
Also, Ive noticed that the "Install APK" step fails with the log as attached [here](https://drive.google.com/file/d/1bz5KrrmQtjrS1I8ABYez6-HMuByG6lAt/view?usp=sharing) , although I am not sure that it is related to the failure of the test generation as per the logs [here](https://drive.google.com/file/d/17GGNbAp_wc0MKRIGAYpWgM3CWc8FZGHR/view?usp=sharing)

**Comment by hanada31** [comment]
It seems like the apk for GUI exploration is not built successfully.
The related codes are in "buildApk.bat" and "buildApk2.bat".
Maybe you could check whether the paths of "dx.bat“ and "aapt.exe" have been added to the system environment variable _path_.

**Comment by smilinrobin** [comment]
Yes, I believe that is the issue. It seems to be related to my Android SDK setup. Thanks for the help. Closing out the issue.
